### PR TITLE
handle validation of login form by Yup library

### PR DESCRIPTION
**Pull request by MaryPG21**

### CODE REVIEW

**Review by samikia — APPROVED** [review]
thanks, keep going on

**Review by hutan88 — APPROVED** [review]
Somthing Wrong

**Review by hutan88 — COMMENTED** [review]
i have error after run


Compiled with problems:X

ERROR in ./src/layouts/MainPage.jsx 7:0-38

Module not found: Error: Cannot find file: 'main.jsx' does not match the corresponding name on disk: '.\src\components\Main.jsx'.

**Review by mhmdrezanaderi — APPROVED** [review]
Thanks

**Pull request merged**
